version: '3.5'  

services: 
    frontend:
      build: 
        context: .
        dockerfile: Dockerfile-frontend
      ports: 
        - 5000:5000
    backend:
      build:
        context: .
        dockerfile: Dockerfile-backend
      ports: 
        - 8000:8000
      volumes:
        - ./logs.txt:/mydir/logs.txt
      environment:
        REDIS: redis
    redis:
      image: redis
      volumes:
        - ./redis_data:/data
      entrypoint: ["redis-server","--appendonly","yes"]
