version: '3.5'  

services: 
    frontend:
      build: 
        context: .
        dockerfile: Dockerfile-frontend
      depends_on: 
        - backend
    backend:
      build:
        context: .
        dockerfile: Dockerfile-backend
      volumes:
        - ./logs.txt:/mydir/logs.txt
      environment:
        REDIS: redis
        DB_USERNAME: postgres
        DB_PASSWORD: example
        DB_NAME: postgres
        DB_HOST: db
      depends_on: 
        - redis
        - db
    redis:
      image: redis
      volumes:
        - ./redis_data:/data
      entrypoint: ["redis-server","--appendonly","yes"]
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db
      volumes:
        - backend_db:/var/lib/postgresql/data
    reverse:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports: 
        - 80:80
      depends_on: 
        - frontend
        - backend

volumes:
  backend_db:

