version: '3.5'  

services: 
    frontend:
      build: 
        context: .
        dockerfile: Dockerfile-frontend
      ports: 
        - 5000:5000
    backend:
      build:
        context: .
        dockerfile: Dockerfile-backend
      ports: 
        - 8000:8000
      volumes:
        - ./logs.txt:/mydir/logs.txt
      environment:
        REDIS: redis
        DB_USERNAME: postgres
        DB_PASSWORD: example
        DB_NAME: postgres
        DB_HOST: db
    redis:
      image: redis
      volumes:
        - ./redis_data:/data
      entrypoint: ["redis-server","--appendonly","yes"]
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db
      volumes:
        - backend_db:/var/lib/postgresql/data

volumes:
  backend_db:

